### PR TITLE
support Scala Native

### PR DESCRIPTION
**Pull request by aoiroaoino**
first support: core, state
```
> show coreNative/nativeMissingDependencies
[info] * @java.net.URI
[info] * @java.net.URI::init_class.java.lang.String
[info] * @java.net.URI::toString_class.java.lang.String
[success] Total time: 4 s, completed 2017/03/17 0:27:58
> show stateNative/nativeMissingDependencies
[info] *
[success] Total time: 1 s, completed 2017/03/17 0:28:05
> show testNative/nativeMissingDependencies
[info] *
[success] Total time: 1 s, completed 2017/03/17 0:28:16
```
we need remove `java.net.URI` ...? :thinking:  /cc @densh @MasseGuillaume
https://github.com/julien-truffaut/Monocle/blob/v1.4.0/core/shared/src/main/scala/monocle/std/String.scala#L35-L36

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Nice! About `java.net.URI` does it mean it would blow up at runtime or compile time if you try to use `URI` natively?

**Comment by xuwei-k** [comment]
I think compile time

**Comment by aoiroaoino** [comment]
runtime ...?
```
object Main {
  ...
  val uri = monocle.std.string.stringToURI.getOption("http://example.com")
}
```
```
> testNative/compile
[info] Compiling 1 Scala source to /Users/aoino/git/Monocle/testNative/target/scala-2.11/classes...
[success] Total time: 1 s, completed 2017/03/17 20:00:50
> testNative/run
[info] Linking NIR (623 ms)
[error] cannot link: @java.net.URI
[error] cannot link: @java.net.URI::init_class.java.lang.String
[error] cannot link: @java.net.URI::toString_class.java.lang.String
[error] unable to link
[error] (testNative/*:nativeLink) unable to link
[error] Total time: 1 s, completed 2017/03/17 20:00:53
```

**Comment by xuwei-k** [comment]
The `run` task depends on the `nativeLink` task

- https://github.com/scala-native/scala-native/blob/v0.1.0/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePlugin.scala#L32
- https://github.com/scala-native/scala-native/blob/v0.1.0/sbt-scala-native/src/main/scala/scala/scalanative/sbtplugin/ScalaNativePluginInternal.scala#L406


Your `cannot link` error is during `nativeLink` task, not runtime.

- compile or package: create `.nir` files from "Scala sources". no errors if there is MissingDependencies
- nativeLink: create executable binary file from `.nir` files. error if there is MissingDependencies

**Comment by julien-truffaut** [comment]
Ok so it means, you will not be able to use `stringToURI` in native but as you cannot deal with `java.net.URI` natively, I don't think it will be an issue.

**Comment by julien-truffaut** [comment]
👍

**Comment by aoiroaoino** [comment]
@julien-truffaut @xuwei-k 
thanks!

**Pull request merged**
