### PR TITLE
fix #353 delete release notes pre 1.0

### LINKED ISSUE #353: Conflate release notes
We have release notes in 3 different locations:
- `/notes` for < 1.0
- wiki for 1.0
- website for > 1.0

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Still need to migrate 1.0 release from the wiki

**Comment by aoiroaoino** [comment]
Sorry for the late reply. 😓 
LGTM 👍

**Comment by aoiroaoino** [comment]
I would like to confirm just in case; Is policy to be integrated into the website?

**Comment by julien-truffaut** [comment]
Thanks @aoiroaoino, I think we use to publish to the website on each commit to master but it seems broken. I will create an issue

**Pull request merged**
