### PR TITLE
use sbt-microsite for docs

### LINKED ISSUE #401: replace website with sbt-microsites
see https://47deg.github.io/sbt-microsites/docs/settings.html

### PR DESCRIPTION
**Pull request by julien-truffaut**
fix #401 

There are still some issues:
- syntax highlighting seems random https://github.com/47deg/sbt-microsites/issues/70
- I had to revert the main scala version to 2.11 because sbt-micro-site is not released for 2.12 https://github.com/47deg/sbt-microsites/issues/82
- colour and logos are not specific to monocle but since I have 0 artistic talent, I would prefer to delegate to someone else :) It is also related to https://github.com/julien-truffaut/Monocle/issues/375

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
https://github.com/47deg/sbt-microsites/issues/70 is now fixed after https://github.com/47deg/sbt-microsites/releases/tag/v0.3.1 has been released ;)

**Comment by julien-truffaut** [comment]
I upgraded sbt-microsite which fixes the two main issues: syntax highlighting and scala 2.12

**Comment by julien-truffaut** [comment]
I reviewed the website format such as we get the equivalent of the README in the front page and then we use doc layout for the rest of the resources.

I know that @NightRa preferred that we kept a descriptive README but it makes the snippet likely to be incorrect as we cannot use tut (see https://github.com/julien-truffaut/Monocle/issues/382). 

Except if you feel this is going completely in the wrong direction, I would like to merge and user test the website with  `sbt-microsites`. If they are some fundamental issues, we can always rollback.

**Comment by julien-truffaut** [comment]
I publish from this branch to the website for people to get a better opinion:
http://julien-truffaut.github.io/Monocle/

**Comment by julien-truffaut** [comment]
Going to merge, I think it is a good improvement over the existing solution and I would rather not maintain the existing ad-hoc solution which was a copy-paste from cats.

**Comment by xuwei-k** [comment]
Should we remove sbt-ghpages?

**Comment by julien-truffaut** [comment]
good point, yes we can remove it. It comes with sbt-microsites

**Pull request merged**
