### PR TITLE
Add Equal instance for optics in test

### PR DESCRIPTION
**Pull request by mjjc**
As per #451

### CODE REVIEW

**Comment by julien-truffaut** [comment]
nice, could you move the tests to another file? `MacroOutSideMonocleSpec` is here to check macro in another package file than monocle.

**Comment by mjjc** [comment]
Right, now it makes more sense.

**Comment by mjjc** [comment]
Previous version was easily extensible to polymorphic optics, so I did that.

**Comment by julien-truffaut** [comment]
Thanks @mjjc 👍

**Pull request merged**
