### PR TITLE
Add Optional documentation, sbt-microsite ready

### PR DESCRIPTION
**Pull request by mdulac**
New PR for Optional documentation, sbt-microsite ready

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Thank you very much, can you also update `menu.yml`

Also would you mind to squash your commits into a single one?

**Comment by mdulac** [comment]
Done :)

**Comment by julien-truffaut** [comment]
Thanks a lot @mdulac, I will merge and update the scala shed to tut shed.

**Comment by julien-truffaut** [comment]
👍

**Pull request merged**
