### PR TITLE
execute packageSrc in travis-ci

### PR DESCRIPTION
**Pull request by xuwei-k**
avoid regression https://github.com/julien-truffaut/Monocle/issues/492

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Good idea 👍

**Comment by julien-truffaut** [comment]
Btw why travis passed after this changed? I would have expected to fail because we haven't fixed https://github.com/julien-truffaut/Monocle/issues/492

**Comment by n4to4** [comment]
@julien-truffaut 
@xuwei-k merged https://github.com/julien-truffaut/Monocle/pull/493 and #492 had been fixed

**Comment by julien-truffaut** [comment]
Oh I missed it, you're too fast!

**Comment by n4to4** [comment]
Please rename the files again if you prefer `PlatformSpecificStringOptics.scala`. I was wondering what should it be called.

**Comment by julien-truffaut** [comment]
@n4to4 it is perfect, thanks.

**Pull request merged**
