### PR TITLE
fix Scala 2.13 build

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Thanks @xuwei-k

**Comment by xuwei-k** [comment]
still fail `doc` task in the `Release` stage 😢 

```
[error] /home/travis/build/[secure]/Monocle/generic/src/main/scala/monocle/generic/internal/CoproductToDisjunction.scala:5:1: Could not find any member to link for "shapeless.Coproduct".
[error] /**
[error] ^
[error] /home/travis/build/[secure]/Monocle/generic/src/main/scala/monocle/generic/internal/DisjunctionToCoproduct.scala:5:1: Could not find any member to link for "Either".
[error] /**
[error] ^
[error] two errors found
```

```
[error] (genericJVM / Compile / doc) Scaladoc generation failed
[error] (genericJS / Compile / doc) Scaladoc generation failed
```


https://travis-ci.org/julien-truffaut/Monocle/jobs/564965176#L716
https://github.com/julien-truffaut/Monocle/blob/303a18a411596e8b61895528d2e5480f47d6e481/generic/src/main/scala/monocle/generic/internal/CoproductToDisjunction.scala#L6

**Comment by julien-truffaut** [comment]
Do you know what is the correct syntax for scala doc? Alternatively, we can just remove the `[[...]]`

**Comment by xuwei-k** [comment]
`[[...]]` is correct syntax. We should remove `[[...]]` or add more settings if reference external libs. https://github.com/ThoughtWorksInc/sbt-api-mappings

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/blob/9fa25de84cf6fb521aa5f161c866837200ec17c4/main/src/main/scala/sbt/Keys.scala#L329-L330

**Comment by julien-truffaut** [comment]
Ok I will remove `[[..]]` thanks Kenji

**Comment by julien-truffaut** [comment]
https://github.com/julien-truffaut/Monocle/pull/692

**Pull request merged**
