### PR TITLE
fix #251 add learning resources to the website

### LINKED ISSUE #251: add learning resources to the website
e.g. links toward slides, blog posts, presentation

### PR DESCRIPTION
**Pull request by julien-truffaut**
Please tell me if you have any other resources to add

### CODE REVIEW

**Comment by NightRa** [comment]
1. Seperate recorded talks from slides
2. Add my slides: Optics with Monocle: "Modeling The Part and The Whole"  - http://www.slideshare.net/IlanGodik/optics-with-monocle-modeling-the-part-and-the-whole
3. Add a link to a comparison post about Monocle vs Scalaz lens vs Shapeless lenses. (need to make that document too, possibly as a different PR)
4. Consider reordering; what is the order of things someone would like to go over materials? Maybe Videos -> Slides -> Blog?

**Comment by julien-truffaut** [comment]
good ideas, I added your slides and separated presentations from slides. I agree, we can a comparison with other optics library in another PR.

**Comment by julien-truffaut** [comment]
@1ambda What name do you want me to use? At the moment I put: by [Hoon](https://github.com/1ambda) but for everyone else I used their complete name.

**Comment by 1ambda** [comment]
@julien-truffaut could you modify `Hoon` to `Hoon Park`? :)

**Comment by julien-truffaut** [comment]
@1ambda done

**Comment by julien-truffaut** [comment]
@1ambda @aoiroaoino are you fine with the Japanese / Korean section? We can reorganise once we get more content

**Comment by 1ambda** [comment]
@julien-truffaut Sure :+1:  I am glad to introduce a great scala optics library to Korean developers

**Comment by julien-truffaut** [comment]
np, going to merge this. I will publish the website tonight

**Comment by aoiroaoino** [comment]
:+1:

**Pull request merged**
