### PR TITLE
Sbt 1.3.6

### PR DESCRIPTION
**Pull request by pascalh**
Replaces https://github.com/julien-truffaut/Monocle/pull/781

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Thanks, @pascalh.

Why did you transform `case` from syntax classes? Do you know if it is backwards compatible?

**Comment by pascalh** [comment]
The idea was that these classes are only used for internal conversion to enable operator syntax, hence the change should not impact the end user. 
When I raised the PR I was under the assumption that people would not use these classes in their code. I would not merge this in if the assumption turns out to be false though ;)

**Comment by julien-truffaut** [comment]
I also think it doesn't impact end-user but it will break binary compatibility. We can do it but it would be better if we could upgrade sbt without breaking compatibility.

**Comment by cquiroz** [comment]
I don’t get how an sbt upgrade requires a code change

**Comment by julien-truffaut** [comment]
We are on sbt 1.3.10 now.

**Pull request closed without merging**
