### PR TITLE
upgrade deps for scala 2.12-RC1, missing shapeless and refined

### LINKED ISSUE #216: Release a version for Scala 2.12-RC2

### PR DESCRIPTION
**Pull request by julien-truffaut**
fix #216

waiting for shapeless and refined release

### CODE REVIEW

**Comment by fthomas** [comment]
refined is also waiting for shapeless

**Comment by julien-truffaut** [comment]
It seems we will need to wait for RC2, see http://www.scala-lang.org/news/2.12.0-RC1

**Comment by fthomas** [comment]
refined is now available for 2.12.0-RC2

**Comment by julien-truffaut** [comment]
Thanks @fthomas 

next dependency: https://github.com/typelevel/discipline/issues/27

**Pull request closed without merging**
