### PR TITLE
Update refined to 0.8.4

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by fthomas** [comment]
All Scala.js builds failed with errors like this:
```
org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 0.6.17 (supported: 0.6.0, 0.6.13, 0.6.3, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15): /home/travis/.ivy2/cache/eu.timepit/refined_sjs0.6_2.12/jars/refined_sjs0.6_2.12-0.8.4.jar:eu/timepit/refined/macros/RefineMacro$$typecreator5$1.sjsir
```
Probably because refined is on Scala.js 0.6.20 while Monocle is on 0.6.16.

**Comment by julien-truffaut** [comment]
Could you try to upgrade scala-js in monocle at the same time?

**Comment by fthomas** [comment]
Done. I also needed to update sbt to 0.13.16 to fix a `java.lang.NoSuchMethodError: sbt.package$.Zero()Lsbt/Global$;` on startup.  Let's see what Travis says about this now.

**Comment by julien-truffaut** [comment]
Awesome, thanks Thomas

**Pull request merged**
