### PR TITLE
Update to Cats 1.1.0

### PR DESCRIPTION
**Pull request by pettyjamesm**
Tests passed for me locally, but with dependency version issues that seem to be isolated to `newts`. I suspect the relevant issue there is: https://github.com/julien-truffaut/newts/issues/22

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Thanks @pettyjamesm, it might be better to bump newts first

**Comment by pettyjamesm** [comment]
@julien-truffaut I'm not familiar with the newts at all, is that likely as simple as just editing the build.sbt in that repo too? Do you want me to submit a separate PR there?

**Comment by julien-truffaut** [comment]
yes it should be as straightforward as that, it is supposed to be a minor cats upgrade. If you have time, it would be great.

**Comment by pettyjamesm** [comment]
Newts PR: https://github.com/julien-truffaut/newts/pull/27

**Comment by julien-truffaut** [comment]
I released newts 0.3.1 with your PR.

**Comment by pettyjamesm** [comment]
Updated the PR to use newts 0.3.1

**Comment by julien-truffaut** [comment]
Thanks @pettyjamesm

**Comment by pettyjamesm** [comment]
Any idea when this will land in a new release version?

**Comment by julien-truffaut** [comment]
@pettyjamesm `1.5.1-cats` is released

**Pull request merged**
