### PR TITLE
Rename compose to and then

### PR DESCRIPTION
**Pull request by debian0501**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Thanks a lot @debian0501 

I think those changes were only required for `core`, `dot-syntax` and `macro` modules. The other modules should be deleted in this branch. Anyway, it does hurt.

I noticed a couple of extra white spaces added, you may want to run `sbt scalafmt`

**Comment by debian0501** [comment]
ok, done. Should I still remove the other directories?

**Comment by julien-truffaut** [comment]
Perfect, thanks. No that's ok, we will do in a subsequent PR. It is easier to review the changes.

**Comment by debian0501** [comment]
how are we going to handle this. Should there be also a new issue for change, or should I simply create a new PR?

**Comment by julien-truffaut** [comment]
@debian0501 good point, I created https://github.com/julien-truffaut/Monocle/issues/803

**Pull request merged**
