### PR TITLE
renamed getOrModify to matching

### PR DESCRIPTION
**Pull request by julien-truffaut**
I never liked the name `getOrModify` but I couldn't find the equivalent in haskell lens.

I completely missed it: https://hackage.haskell.org/package/lens-4.12.3/docs/src/Control-Lens-Prism.html#matching

### CODE REVIEW

**Comment by NightRa** [comment]
I personally don't think it's a good idea to break compatibility for this kind of name change.
Also, the name `matching` isn't any more intuitive than `getOrModify`.

**Comment by julien-truffaut** [comment]
You're right I might have overlooked the argument of binary compatibility. 

The good thing is that I believe that `getOrModify` is rarely used, so I don't think it would be too harmful to rename it in the next non binary compatible release (1.2.0). Btw, I don't know if you noticed but I let `getOrModify` but deprecated it.

`matching` talks more to me that `getOrModify` but that's probably personal.

**Comment by julien-truffaut** [comment]
@NightRa do you think the aliasing + deprecation is acceptable or we should rather revert this change?

**Comment by julien-truffaut** [comment]
@NightRa I rolledback this change, I agree with you there is no point to make such a change now.

**Pull request merged**
