### PR TITLE
Add optics for scalaz.Either3

### PR DESCRIPTION
**Pull request by aoiroaoino**
#241

### CODE REVIEW

**Comment by julien-truffaut** [comment]
great, can you also add `EitherOptics` to the `StdInstances` trait

**Comment by aoiroaoino** [comment]
hmm, what does it mean?
I was add `Either3Optics` to the `StdInstances`.
https://github.com/julien-truffaut/Monocle/pull/242/files#diff-4bc571cceb5f745952dcd21f6ff5f337R35

**Comment by julien-truffaut** [comment]
@aoiroaoino sorry my bad, I don't know how did I miss it... 

Thanks!

**Comment by aoiroaoino** [comment]
no problem :smile:

**Pull request merged**
