### PR TITLE
Field syntax for AppliedLens

### PR DESCRIPTION
**Pull request by julien-truffaut**
Partially implement #735

```scala
case class Foo(i: Int, bar: Bar)
case class Bar(b: Boolean, s: String)
val foo = Foo(5, Bar(true, "Hello"))

foo.optic.field(_.bar).field(_.b).get shouldEqual foo.bar.b
```

We should also be able to chain fields like `_.bar.b` but there is currently a compiler error.

We can repeat the process for all optics, applied optics.

### CODE REVIEW

**Comment by cquiroz** [comment]
Maybe I can try to do the same for another of the optics, Prism perhaps?

**Comment by julien-truffaut** [comment]
> Maybe I can try to do the same for another of the optics, Prism perhaps?

Sure. Do you mean add `field` to `Prism` / `AppliedPrism` or add another method on `AppliedLens` that simplifies composing with the branch of a sealed trait?

**Comment by cb372** [comment]
I know a bit about macros and this looks reasonable to me 😄

**Comment by julien-truffaut** [comment]
Thanks @cb372 for the review. Do you have an idea of how we can generalise that macro to other optics/applied optics without completely duplicating the code?

**Comment by cb372** [comment]
Yes that should be do-able, but I'll have to have a look at the rest of the code. I haven't been following the progress of 3.x so I need to catch up. Is there any kind of design doc I should look at before I dive into the code?

**Comment by julien-truffaut** [comment]
It is not really formalised. We have a couple of ideas but nothing really set in stone. This is probably the best plan we have so far: https://github.com/julien-truffaut/Monocle/issues/714.

Regarding this particular point, we are trying to have a convenient syntax to compose optics for the most common scenarios such as a user can do:

```scala
someOptioc.field(_.foo)
```

instead of this syntax in Monocle 2:

```scala
someOptic composeLens GenLens[Bar](_.foo)
```

We are trying to implement `field` this method on all optics (`Lens`, `Prism`, `Iso`, ...) and all applied optics (`AppliedLens`, `AppliedPrism`, `AppliedIso`).

I am not sure where these methods should be defined. Should we have them on optics/applied optics classes or should we "pimp" them on a separate module.

**Pull request merged**
