### PR TITLE
Use github actions

### PR DESCRIPTION
**Pull request by cquiroz**
This PR should let us use git hub actions instead of travis, at least on the 3.x branch
Some important notes:
* Releases should be enabled via `sbt-ci-releases` but we need to setup credentials and we won't really know if it works until we merge with master
* I didn't try to setup the doc publication yet
* I didn't enable scalafmt check as it seems a bunch of files aren't yet formatted

### CODE REVIEW

**Comment by julien-truffaut** [comment]
LGTM but I have no experience with GitHub Actions. Was it run in this PR?

**Comment by cquiroz** [comment]
It ran on my fork
https://github.com/cquiroz/Monocle/commit/fce537b6c298659c2d8b90d9d943cfced51f5c76/checks?check_suite_id=368463976

**Comment by cquiroz** [comment]
It should run as soon as we merge. As usual these things require a bit of experimentation

**Comment by julien-truffaut** [comment]
Yes, I would be surprised if it works for the first time. At least, it never happens to me :)

**Comment by cquiroz** [comment]
It ran here
https://github.com/julien-truffaut/Monocle/commit/2575cdb340843e38857969b9d680383e72d0b31c/checks?check_suite_id=368534008

**Pull request merged**
