### PR TITLE
add maven badge

### LINKED ISSUE #268: add Maven central badge
e.g. https://github.com/fthomas/refined or https://github.com/http4s/http4s

### PR DESCRIPTION
**Pull request by julien-truffaut**
Thanks to @fthomas help!

### CODE REVIEW

**Comment by aoiroaoino** [comment]
:+1: 

@fthomas thanks! :smile:

**Comment by fthomas** [comment]
You're welcome :-)

**Comment by julien-truffaut** [comment]
@aoiroaoino cheers, if you want you can merge the PR after you approve it.

**Comment by aoiroaoino** [comment]
@julien-truffaut ok, I will :)

**Pull request merged**
