### PR TITLE
[DONT MERGE] Release 1.2.1

### PR DESCRIPTION
**Pull request by julien-truffaut**
tentative release for 1.2.1

Potential issue, we made a major upgrade of shapeless (2.2.5 -> 2.3.0). Shall we revert shapeless to 2.2.5?

### CODE REVIEW

**Comment by julien-truffaut** [comment]
we need to revert shapeless to 2.2.5 and refined to 0.3.2

**Comment by julien-truffaut** [comment]
@aoiroaoino @NightRa @japgolly If you have a min, would you mind to review this release? I run mima and everything seems to be backward compatible with 1.2.0.

**Comment by japgolly** [comment]
Most libraries are backwards-compatible in their minor releases but rarely forwards-compatible. I tend to keep the *z* in versions *x.y.z* low in library deps. Example I just released scalajs-react the other day and I used  7.2.1 for official Scala.JS support but ignored the 7.2.2 release because I want users to be able to use 7.2.1+ not 7.2.2+. It might be a good policy to go with the minimum major versions as a library. Up to you.

Next, I've not used mima so I don't know about those settings.

Otherwise LGTM :+1: .
Just remember to change the date in the changelog before you hit the release button. :smile:

**Comment by julien-truffaut** [comment]
thanks @japgolly I didn't think about using low patch version in a library for the arguments you mentioned. However, I think it is more convenient to get high patch version such as people get the latest bug fixes transitively. I am more than open to change that if it makes sense for users.

Good point about the release date!

**Comment by julien-truffaut** [comment]
Release is done, I will cherry-pick the commit back to master. @NightRa suggested to use `git rebase -i` next time.

**Comment by NightRa** [comment]
:+1:

**Pull request closed without merging**
