### PR TITLE
Implements mapping method in Iso, to lift a Iso[A, S] to an Iso[F[A],…

### PR DESCRIPTION
**Pull request by mdulac**
… F[S]]

### CODE REVIEW

**Comment by julien-truffaut** [comment]
nice :)

Even though the laws you added are completely correct, I am not sure we should include them as they will slow down the tests. Maybe we could only test `mapping` for a single optic as the implementation is fairly straightforward?

**Comment by mdulac** [comment]
Sure, and that's what I did initially.
I will commit a single test with the Id Functor and remove the laws checks. Is that better ?

**Comment by julien-truffaut** [comment]
perfect, thank you!

**Comment by mdulac** [comment]
Done :)

**Comment by julien-truffaut** [comment]
👍 thanks @mdulac

**Pull request merged**
