### PR TITLE
add Option and Either Prism in Prism's companion object

### PR DESCRIPTION
**Pull request by julien-truffaut**
do you think it makes sense to define them in the companion object of Prism?

### CODE REVIEW

**Comment by cquiroz** [comment]
It seems fine, they are a bit hard to find now living on `std`.

**Comment by julien-truffaut** [comment]
I agree but `Iso` seems to be a less clear cut. Should we put `Iso[List[A], Vector[A]]` in the companion object of `Iso`? what about the other way around? should we do all Seq combinations?

**Comment by cquiroz** [comment]
I also wondered about adding these on each Optic, considering that it could be nice to have a very small kernel

**Comment by julien-truffaut** [comment]
Yes, it is tricky to know where to draw the line. 

IMO, the most important is that the kernel will be very stable. For example, I am not sure if adding a method to a companion object break binary compatibility.

**Pull request merged**
